# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# https://www.jianshu.com/p/ac18956b0bc0
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - replacements:
      darwin: darwin
      linux: linux
      386: 386
      amd64: amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "make"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
