title: zzz
frequency: 1
dirfilter:
- tmp
- .git
- scripts
- vendor
- logs
- assets
- .github
- data
ext:
- go
- js
- tmpl
- ini
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - rm -rf logs/run_away.log
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go
