title: zzz
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
- assets
- .github
- data
ext:
- go
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - rm -rf logs/run_away.log
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go
  after:
  - echo ""
